openapi: 3.0.0
info:
  title: ScienceBase Vocab API
  description: 'Lists of terms (and lookup values) used in catalog and other apps.  Provides REST services used by other apps.'
  version: '1.15.4'
servers:
- url: https://beta.sciencebase.gov/vocab
- url: https://sciencebase.gov/vocab
  variables: {}
paths:
  /categories:
    get:
      summary: All categories
      description: The categories endpoint, returns all terms by term, vocabulary, and category.
      parameters:
        - name: q
          in: query
          description: Specified search term
          required: false
          schema:
            type: string
        - name: max
          in: query
          description: Number of results to display per page
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: Number of items to skip before starting to collect result set
          required: false
          schema:
            type: integer
      tags:
        - Categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
        '404':
          description: 'Term does not exist, or you do not have permissions to view it.'
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
  /category/{id, name}:
    get:
      summary: Category by id or name
      description: The category by id or name endpoint returns a category for a given ID or Name.
      parameters:
        - name: 'id, name'
          in: path
          description: ID or Name of folder
          required: true
          schema:
            type: string
      tags:
        - Category
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
        '404':
          description: 'Folder does not exist, or you do not have permissions to view it.'
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
  /category/{id}:
    put:
      tags:
      - Category
      summary: Updates a category
      description: "Updates the properties of the specified category by ID."
      operationId: /category2
      parameters:
      - name: 'id'
        in: path
        description: ID of the subfolder to be edited
        required: true
        schema:
          type: string
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=F5683F6F664330999D4DD81433961BA0; myusgs.quiet=1; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.1114365831.1511800293; _gat=1
        example: JSESSIONID=F5683F6F664330999D4DD81433961BA0; myusgs.quiet=1; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.1114365831.1511800293; _gat=1
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json, text/javascript, */*; q=0.01
        example: application/json, text/javascript, */*; q=0.01
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/category/5a2319afe4b0b59b7983e729/editForm
        example: https://beta.sciencebase.gov/vocab/category/5a2319afe4b0b59b7983e729/editForm
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              example:
                id: 5a2319afe4b0b59b7983e729
                parentId: 4f4e475be4b07f02db47de34
                parentItemId: ''
                name: 1dirctestzzzz
                label: ''
                description: ''
                nodeType: category
                browseCategory: ''
                appliesTo: []
                backTo: ''
                permissions:
                  write:
                    acl: []
                scheme: https://beta.sciencebase.gov/vocab/category
                uri: https://beta.sciencebase.gov/vocab/category/5a2319afe4b0b59b7983e729
              $ref: '#/components/schemas/~1categoryrequest3'
            example: '{"id":"5a2319afe4b0b59b7983e729","parentId":"4f4e475be4b07f02db47de34","parentItemId":"","name":"1dirctestzzzz","label":"","description":"","nodeType":"category","browseCategory":"","appliesTo":[],"backTo":"","permissions":{"write":{"acl":[]}},"scheme":"https://beta.sciencebase.gov/vocab/category","uri":"https://beta.sciencebase.gov/vocab/category/5a2319afe4b0b59b7983e729"}'
        required: true
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
      - Category
      summary: Deletes the category
      description: "Deletes the specified category."
      operationId: /category3
      parameters:
      - name: 'id'
        in: path
        description: ID of the subfolder to be edited
        required: true
        schema:
          type: string
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=F5683F6F664330999D4DD81433961BA0; myusgs.quiet=1; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.1114365831.1511800293; _gat=1
        example: JSESSIONID=F5683F6F664330999D4DD81433961BA0; myusgs.quiet=1; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.1114365831.1511800293; _gat=1
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: '*/*'
        example: '*/*'
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/category/5a2319afe4b0b59b7983e729/editForm
        example: https://beta.sciencebase.gov/vocab/category/5a2319afe4b0b59b7983e729/editForm
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /category:
    post:
      tags:
      - Category
      summary: Create a subfolder
      description: Create a subfolder.
      operationId: /category1
      parameters:
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=3487134AD47D9ABB1F5BF17595704268; myusgs.recent=1; _gat=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.1114365831.1511800293
        example: JSESSIONID=3487134AD47D9ABB1F5BF17595704268; myusgs.recent=1; _gat=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.1114365831.1511800293
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json, text/javascript, */*; q=0.01
        example: application/json, text/javascript, */*; q=0.01
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/category/new/editForm?parentId=4f4e475be4b07f02db47de34&nodeType=category&backTo=parent
        example: https://beta.sciencebase.gov/vocab/category/new/editForm?parentId=4f4e475be4b07f02db47de34&nodeType=category&backTo=parent
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              example:
                id: ''
                parentId: 4f4e475be4b07f02db47de34
                parentItemId: ''
                name: Test Subfolder
                label: ''
                description: ''
                nodeType: category
                browseCategory: ''
                appliesTo: []
                backTo: parent
                permissions:
                  write:
                    acl: []
              $ref: '#/components/schemas/~1categoryrequest'
            example: '{"id":"","parentId":"4f4e475be4b07f02db47de34","parentItemId":"","name":"Test Subfolder","label":"","description":"","nodeType":"category","browseCategory":"","appliesTo":[],"backTo":"parent","permissions":{"write":{"acl":[]}}}'
        required: true
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /vocabularies:
    get:
      summary: All vocabularies
      description: The vocabularies endpoint, returns all vocabularies.
      parameters:
        - name: q
          in: query
          description: Specified search term
          required: false
          schema:
            type: string
        - name: max
          in: query
          description: Number of results to display per page
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: Number of items to skip before starting to collect result set
          required: false
          schema:
            type: integer
      tags:
        - Vocabularies
      responses:
        '200':
          description: A list of vocabularies
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
        '404':
          description: 'Term does not exist, or you do not have permissions to view it.'
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object    
  /vocabulary/{id}:
    get:
      summary: Vocabulary by id
      description: The vocabulary by id endpoint returns a vocabulary and it's terms for a given ID.
      parameters:
        - name: 'id'
          in: path
          description: ID of vocabulary
          required: true
          schema:
            type: string
      tags:
        - Vocabulary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
        '404':
          description: 'Folder does not exist, or you do not have permissions to view it.'
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
    put:
      tags:
      - Vocabulary
      summary: Updates a vocabulary
      description: "Updates the properties of the specified vocabulary by ID."
      operationId: /vocabulary2
      parameters:
      - name: 'id'
        in: path
        description: ID of the folder to be edited
        required: true
        schema:
          type: string
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _gat=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144
        example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _gat=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json, text/javascript, */*; q=0.01
        example: application/json, text/javascript, */*; q=0.01
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/vocabulary/5a24b175e4b0b59b7983e72c/editForm
        example: https://beta.sciencebase.gov/vocab/vocabulary/5a24b175e4b0b59b7983e72c/editForm
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              example:
                id: 5a24b175e4b0b59b7983e72c
                parentId: 596e5e17e4b046188688dc04
                name: dirctestvocabpost2
                key: ''
                label: ''
                description: ''
                nodeType: vocabulary
                termClass: ''
                browseCategory: ''
                appliesTo: []
                backTo: ''
                permissions:
                  write:
                    acl: []
                scheme: https://beta.sciencebase.gov/vocab/category/test
                uri: https://beta.sciencebase.gov/vocab/category/5a24b175e4b0b59b7983e72c
                termScheme: https://beta.sciencebase.gov/vocab/category/test/dirctestvocabpost
                termsUri: https://beta.sciencebase.gov/vocab/5a24b175e4b0b59b7983e72c/terms
              $ref: '#/components/schemas/~1vocabularyrequest9'
            example: '{"id":"5a24b175e4b0b59b7983e72c","parentId":"596e5e17e4b046188688dc04","name":"dirctestvocabpost2","key":"","label":"","description":"","nodeType":"vocabulary","termClass":"","browseCategory":"","appliesTo":[],"backTo":"","permissions":{"write":{"acl":[]}},"scheme":"https://beta.sciencebase.gov/vocab/category/test","uri":"https://beta.sciencebase.gov/vocab/category/5a24b175e4b0b59b7983e72c","termScheme":"https://beta.sciencebase.gov/vocab/category/test/dirctestvocabpost","termsUri":"https://beta.sciencebase.gov/vocab/5a24b175e4b0b59b7983e72c/terms"}'
        required: true
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
      - Vocabulary
      summary: Deletes the vocabulary
      description: "Deletes the specified vocabulary folder."
      operationId: /vocabulary3
      parameters:
      - name: 'id'
        in: path
        description: ID of the folder to be edited
        required: true
        schema:
          type: string
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144; _gat=1
        example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144; _gat=1
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: '*/*'
        example: '*/*'
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/vocabulary/5a24b175e4b0b59b7983e72c/editForm
        example: https://beta.sciencebase.gov/vocab/vocabulary/5a24b175e4b0b59b7983e72c/editForm
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /vocabulary:
    post:
      tags:
      - Vocabulary
      summary: Create a vocabulary folder
      description: "Create a vocabulary folder."
      operationId: /vocabulary1
      parameters:
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _gat=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144
        example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _gat=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json, text/javascript, */*; q=0.01
        example: application/json, text/javascript, */*; q=0.01
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/vocabulary/new/editForm?parentId=596e5e17e4b046188688dc04&nodeType=vocabulary&backTo=parent
        example: https://beta.sciencebase.gov/vocab/vocabulary/new/editForm?parentId=596e5e17e4b046188688dc04&nodeType=vocabulary&backTo=parent
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              example:
                id: ''
                parentId: 596e5e17e4b046188688dc04
                name: dirctestvocabpost
                key: ''
                label: ''
                description: ''
                nodeType: vocabulary
                termClass: ''
                browseCategory: ''
                appliesTo: []
                backTo: parent
                permissions:
                  write:
                    acl: []
              $ref: '#/components/schemas/~1vocabularyrequest'
            example: '{"id":"","parentId":"596e5e17e4b046188688dc04","name":"dirctestvocabpost","key":"","label":"","description":"","nodeType":"vocabulary","termClass":"","browseCategory":"","appliesTo":[],"backTo":"parent","permissions":{"write":{"acl":[]}}}'
        required: true
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /terms:
    get:
      summary: All terms
      description: The terms endpoint, returns all terms.
      parameters:
        - name: q
          in: query
          description: Specified search term
          required: false
          schema:
            type: string
        - name: max
          in: query
          description: Number of results to display per page
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: Number of items to skip before starting to collect result set
          required: false
          schema:
            type: integer
      tags:
        - Terms
      responses:
        '200':
          description: A list of vocabularies
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
        '404':
          description: 'Term does not exist, or you do not have permissions to view it.'
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object      
  /term/{id}:
    get:
      summary: Term by id
      description: The term by id endpoint returns a vocabulary and it's terms for a given ID.
      parameters:
        - name: 'id'
          in: path
          description: ID of term
          required: true
          schema:
            type: string
      tags:
        - Term
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
        '404':
          description: 'Folder does not exist, or you do not have permissions to view it.'
          content:
            application/json:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
            application/atom+xml:
              schema:
                type: object
    put:
      tags:
      - Term
      summary: Updates a term
      description: "Updates the properties of the specified term by ID."
      operationId: /term2
      parameters:
      - name: 'id'
        in: path
        description: ID of the term to be edited
        required: true
        schema:
          type: string
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _gat=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144
        example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _gat=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json, text/javascript, */*; q=0.01
        example: application/json, text/javascript, */*; q=0.01
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/term/5a24b5e9e4b0b59b7983e72e/editForm
        example: https://beta.sciencebase.gov/vocab/term/5a24b5e9e4b0b59b7983e72e/editForm
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/~1termrequest14'
        required: true
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
      - Term
      summary: Deletes a term
      description: "Deletes the specified term."
      operationId: /term3
      parameters:
      - name: 'id'
        in: path
        description: ID of the term to be deleted
        required: true
        schema:
          type: string
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144; _gat=1
        example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144; _gat=1
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: '*/*'
        example: '*/*'
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/term/5a24b5e9e4b0b59b7983e72e/editForm
        example: https://beta.sciencebase.gov/vocab/term/5a24b5e9e4b0b59b7983e72e/editForm
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /term:
    post:
      tags:
      - Term
      summary: Create a term
      description: "Creates a term."
      operationId: /term1
      parameters:
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144
        example: JSESSIONID=7352EDA52EABFDFD842526BEA0224870; myusgs.recent=1; _ga=GA1.2.531870748.1511800293; _gid=GA1.2.537161824.1512353144
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov
        example: https://beta.sciencebase.gov
      - name: Accept-Encoding
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: gzip, deflate, br
        example: gzip, deflate, br
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: en-US,en;q=0.9
        example: en-US,en;q=0.9
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      - name: Content-Type
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
        example: application/json
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json, text/javascript, */*; q=0.01
        example: application/json, text/javascript, */*; q=0.01
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: https://beta.sciencebase.gov/vocab/term/new/editForm?parentId=5a24b544e4b0b59b7983e72d&nodeType=term&backTo=parent
        example: https://beta.sciencebase.gov/vocab/term/new/editForm?parentId=5a24b544e4b0b59b7983e72d&nodeType=term&backTo=parent
      - name: X-Requested-With
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: XMLHttpRequest
        example: XMLHttpRequest
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: keep-alive
        example: keep-alive
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/~1termrequest'
        required: true
      responses:
        200:
          description: ''
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
components:
  schemas:
    /categoryrequest:
      title: /categoryRequest
      required:
      - id
      - parentId
      - parentItemId
      - name
      - label
      - description
      - nodeType
      - browseCategory
      - appliesTo
      - backTo
      - permissions
      type: object
      properties:
        id:
          type: string
        parentId:
          type: string
        parentItemId:
          type: string
        name:
          type: string
        label:
          type: string
        description:
          type: string
        nodeType:
          type: string
        browseCategory:
          type: string
        appliesTo:
          type: array
          items:
            type: string
          description: ''
        backTo:
          type: string
        permissions:
          $ref: '#/components/schemas/Permissions'
      example:
        id: ''
        parentId: 4f4e475be4b07f02db47de34
        parentItemId: ''
        name: Test Subfolder
        label: ''
        description: ''
        nodeType: category
        browseCategory: ''
        appliesTo: []
        backTo: parent
        permissions:
          write:
            acl: []
    Permissions:
      title: Permissions
      required:
      - write
      type: object
      properties:
        write:
          $ref: '#/components/schemas/Write'
    Write:
      title: Write
      required:
      - acl
      type: object
      properties:
        acl:
          type: array
          items:
            type: string
          description: ''
    /categoryrequest3:
      title: /categoryRequest3
      required:
      - id
      - parentId
      - parentItemId
      - name
      - label
      - description
      - nodeType
      - browseCategory
      - appliesTo
      - backTo
      - permissions
      - scheme
      - uri
      type: object
      properties:
        id:
          type: string
        parentId:
          type: string
        parentItemId:
          type: string
        name:
          type: string
        label:
          type: string
        description:
          type: string
        nodeType:
          type: string
        browseCategory:
          type: string
        appliesTo:
          type: array
          items:
            type: string
          description: ''
        backTo:
          type: string
        permissions:
          $ref: '#/components/schemas/Permissions'
        scheme:
          type: string
        uri:
          type: string
      example:
        id: 5a2319afe4b0b59b7983e729
        parentId: 4f4e475be4b07f02db47de34
        parentItemId: ''
        name: 1dirctestzzzz
        label: ''
        description: ''
        nodeType: category
        browseCategory: ''
        appliesTo: []
        backTo: ''
        permissions:
          write:
            acl: []
        scheme: https://beta.sciencebase.gov/vocab/category
        uri: https://beta.sciencebase.gov/vocab/category/5a2319afe4b0b59b7983e729
    /vocabularyrequest:
      title: /vocabularyRequest
      required:
      - id
      - parentId
      - name
      - key
      - label
      - description
      - nodeType
      - termClass
      - browseCategory
      - appliesTo
      - backTo
      - permissions
      type: object
      properties:
        id:
          type: string
        parentId:
          type: string
        name:
          type: string
        key:
          type: string
        label:
          type: string
        description:
          type: string
        nodeType:
          type: string
        termClass:
          type: string
        browseCategory:
          type: string
        appliesTo:
          type: array
          items:
            type: string
          description: ''
        backTo:
          type: string
        permissions:
          $ref: '#/components/schemas/Permissions'
      example:
        id: ''
        parentId: 596e5e17e4b046188688dc04
        name: dirctestvocabpost
        key: ''
        label: ''
        description: ''
        nodeType: vocabulary
        termClass: ''
        browseCategory: ''
        appliesTo: []
        backTo: parent
        permissions:
          write:
            acl: []
    /vocabularyrequest9:
      title: /vocabularyRequest9
      required:
      - id
      - parentId
      - name
      - key
      - label
      - description
      - nodeType
      - termClass
      - browseCategory
      - appliesTo
      - backTo
      - permissions
      - scheme
      - uri
      - termScheme
      - termsUri
      type: object
      properties:
        id:
          type: string
        parentId:
          type: string
        name:
          type: string
        key:
          type: string
        label:
          type: string
        description:
          type: string
        nodeType:
          type: string
        termClass:
          type: string
        browseCategory:
          type: string
        appliesTo:
          type: array
          items:
            type: string
          description: ''
        backTo:
          type: string
        permissions:
          $ref: '#/components/schemas/Permissions'
        scheme:
          type: string
        uri:
          type: string
        termScheme:
          type: string
        termsUri:
          type: string
      example:
        id: 5a24b175e4b0b59b7983e72c
        parentId: 596e5e17e4b046188688dc04
        name: dirctestvocabpost2
        key: ''
        label: ''
        description: ''
        nodeType: vocabulary
        termClass: ''
        browseCategory: ''
        appliesTo: []
        backTo: ''
        permissions:
          write:
            acl: []
        scheme: https://beta.sciencebase.gov/vocab/category/test
        uri: https://beta.sciencebase.gov/vocab/category/5a24b175e4b0b59b7983e72c
        termScheme: https://beta.sciencebase.gov/vocab/category/test/dirctestvocabpost
        termsUri: https://beta.sciencebase.gov/vocab/5a24b175e4b0b59b7983e72c/terms
    /termrequest:
      title: /termRequest
      required:
      - id
      - parentId
      - name
      - label
      - description
      - nodeType
      - appliesTo
      - backTo
      - extensions
      type: object
      properties:
        id:
          type: string
        parentId:
          type: string
        name:
          type: string
        label:
          type: string
        description:
          type: string
        nodeType:
          type: string
        appliesTo:
          type: array
          items:
            type: string
          description: ''
        backTo:
          type: string
        extensions:
          $ref: '#/components/schemas/Extensions'
    Extensions:
      title: Extensions
      required:
      - webLinkType
      - itemLinkType
      - linkRelationType
      type: object
      properties:
        webLinkType:
          type: string
        itemLinkType:
          type: string
        linkRelationType:
          type: string
    /termrequest14:
      title: /termRequest14
      required:
      - id
      - parentId
      - name
      - label
      - description
      - nodeType
      - appliesTo
      - backTo
      - extensions
      - scheme
      - uri
      type: object
      properties:
        id:
          type: string
        parentId:
          type: string
        name:
          type: string
        label:
          type: string
        description:
          type: string
        nodeType:
          type: string
        appliesTo:
          type: array
          items:
            type: string
          description: ''
        backTo:
          type: string
        extensions:
          $ref: '#/components/schemas/Extensions'
        scheme:
          type: string
        uri:
          type: string
